# Generated by Django 4.1.7 on 2023-03-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_category',
            field=models.CharField(choices=[('pay of credit card', 'pay of credit card'), ('Mortgage Loans', 'Mortgage Loans'), ('Debt Consolidation Loans', 'Debt Consolidation Loans'), ('Home improvemen', 'Home improvement'), ('Medical expense', 'Medical expense'), ('Travel', 'Travel'), ('Student Loans', 'Student Loans'), ('Other', 'Other')], default='Mortgage Loans', max_length=30),
        ),
    ]
