# Generated by Django 4.1.7 on 2023-03-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_back', '0002_loan_loan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_term',
            field=models.IntegerField(choices=[(12, '12 months'), (24, '24 months'), (36, '36 months'), (48, '48 months'), (72, '72 months'), (80, '80 months')], default=12),
        ),
    ]
