# Generated by Django 4.1.7 on 2023-03-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_back', '0004_alter_loan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ('request_date',)},
        ),
    ]
